---
title: "Untitled"
author: "黃珈綺"
date: "2020/4/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tidyverse")
library("tidyverse")
install.packages("magritter")
library(magrittr)

```
# Q1.
請用 `select()` 從資料 `movies`中 (`ggplot2movies`), 選出欄位名稱從 `title` 到 `votes`, 以及
`Action` 到 `Short`的資料

```{r}
library(pacman)
p_load(ggplot2movies,tidyverse)
head(movies)
str(movies)
select(iris,Sepal.Length:Petal.Width)
select(movies,title:votes,Action:Short)
```
```{r}
movies %>% select(starts_with("r"))
movies %>% select(starts_with("m"))
```

# Q2.
從資料 `movies`中，找出欄位名稱開頭為 `r` or `m`的欄位
```{r}
movies %>%
  select(starts_with("r"),starts_with("m"))

```

# Q3.
請將`iris`資料中數值欄位，全部改為英吋(即除以2.5)，以及將`Species`欄位的資料全部轉為英文大寫，
並輸出資料集為`irisImperial`


```{r}
irisImperial<- iris %>% mutate(Species = toupper(Species),
                Sepal.Width = Sepal.Width/2.5,
                Sepal.Length = Sepal.Length/2.5,
                Petal.Width = Petal.Width/2.5,
                Petal.Length = Petal.Length/2.5)
head(irisImperial)
iris %>% 
  transmute(Sepal.Width=floor(Sepal.Width),
            Species = case_when(
              Species == "setosa" ~toupper(Species),
              Species == "versicolor" ~toupper(Species),
              Species == "virginica" ~toupper(Species),
              TRUE ~ as.character(Species)
            ))
```
